version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: social_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persiste os dados
    ports:
      - "5432:5432"
    healthcheck: # Garante que o serviço FastAPI espera o DB estar pronto
      test: ["CMD-SHELL", "pg_isready -U user -d project_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Serviço da Aplicação FastAPI
  web:
    build: .
    container_name: social_api
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./app:/app/app # Monta o diretório de código para desenvolvimento
    ports:
      - "8000:8000"
    environment:
      # String de conexão do DB (use o nome do serviço 'db' como host)
      DATABASE_URL: postgresql://user:password@db/project_db
    depends_on:
      db:
        condition: service_healthy # Espera o DB estar saudável

# Volumes para persistência de dados
volumes:
  postgres_data: